theme: jekyll-theme-architect

# Site Settings
locale                   : "fa-IR"
dir			                 : "rtl"
title                    : "AitinTech"
description              : "Intelligent Systems"
url                      : "https://AitinTech.ir"
