theme: jekyll-theme-architect

# Site Settings
title                    : "AitinTech"
description              : "Intelligent Systems"
url                      : "https://AitinTech.ir"

# languages
# default langages : "en" 
languages: ["en", "fa"]